from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional


class ResearchState(BaseModel):
    """
    The state tracking single source of truth for AuRA's multi-agent system.
    Tracks state progress, handles document storage, and logs contradictions.
    """
    user_query: str = Field(
        ...,
        description="The active natural language research question from the user (can adapt during self-correction loops)."
    )
    objectives: List[str] = Field(
        default_factory=list,
        description="Decomposed sub-topics generated by the research planner."
    )
    raw_documents: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Text chunks, clean markdown bodies, and matching metadata harvested from the web."
    )
    knowledge_graph: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Extracted factual JSON triples representing nodes and directed relationship edges."
    )
    conflicts: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Log of source contradictions and structural discrepancies found by the auditor."
    )
    compiled_cache: str = Field(
        default="",
        description="Prefix-optimized structured cache string compiling raw scrape bodies."
    )

    # --- STEP 4.3 MEMORY REGISTERS ---
    tie_breaker_queries: List[str] = Field(
        default_factory=list,
        description="Historical log of dynamic searches executed to resolve information divergence."
    )

    active_routing_target: str = Field(
        default="scout_node",
        description="The next execution target state indicator for LangGraph routing logic."
    )
    final_report: Optional[str] = Field(
        default=None,
        description="The compiled minimalist paper-white output report matching citation frameworks."
    )


class BaseAgent:
    """
    Abstract structural interface for all AuRA execution modules.
    Enforces a strict async execution pattern across all worker nodes.
    """

    def __init__(self, name: str, model: str):
        self.name = name
        self.model = model

    async def execute(self, state: ResearchState) -> ResearchState:
        raise NotImplementedError(f"Agent '{self.name}' must implement the async execute interface method.")